# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
  - composer install --dev --no-interaction

script:
  - phpunit -c app/phpunit.xml.dist

notifications:
  email:
    - ju.meunier44@gmail.com
