acme_security_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeSecurityBundle:Default:index }

login:
    pattern: /login
    defaults: { _controller: AcmeSecurityBundle:Security:login }

login_check:
    pattern: /login_check

account:
    pattern: /account
    defaults: { _controller: AcmeSecurityBundle:Security:account }
